// react/app/Gallery.tsx
"use client";

import React from "react";
import styles from "./Gallery.module.css";

export default function Gallery() {

  return (
    <div className={styles.gallery}>
      <img
        src={`https://picsum.photos/400/200`}
        className={styles.img}
        alt="Stocks Image"
      />
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat inventore deleniti delectus quidem. Minus quo quae esse excepturi assumenda quis repudiandae unde exercitationem, error veniam dolorem harum expedita quam facere, qui beatae quia est. Atque consequatur totam, explicabo tenetur illum libero sit perspiciatis facilis, quibusdam voluptas debitis expedita labore magni fugiat fuga laborum ullam! Blanditiis nulla eius eveniet? Pariatur iste error voluptatem mollitia reiciendis minima libero nulla nihil aperiam ipsa?
      </p>
      <img
        src={`https://picsum.photos/400/300`}
        className={styles.img}
        alt="Stocks Image"
      />
      <p>
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fugit, excepturi
        cum doloremque nulla nisi quisquam esse totam aut a nostrum ea voluptas
        aliquam minima consectetur, repudiandae eligendi temporibus dignissimos
        rerum laborum ducimus. Quaerat adipisci eum ipsum totam fuga velit at in
        repudiandae nisi natus quae id sit, explicabo ad laboriosam facere? Commodi
        neque error deleniti corporis accusamus, rerum animi odit asperiores
        molestias sunt. Id magnam, rerum delectus obcaecati incidunt harum minima
        praesentium voluptatum fuga, dicta unde vitae dignissimos exercitationem
        repellendus.
      </p>
      <img
        src={`https://picsum.photos/400/500`}
        className={styles.img}
        alt="Stocks Image"
      />
      <p>
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eius excepturi natus quisquam nesciunt unde distinctio corporis, nam impedit rem voluptatem ab voluptatibus animi quae, vitae adipisci perferendis error! Inventore nulla, voluptatem veniam corporis adipisci consequatur itaque repellat. Voluptatum facere sunt soluta, reprehenderit ad, beatae suscipit ea ullam, molestias atque libero quis eum? Nihil quas nemo, fugiat mollitia atque, similique ratione, quaerat tempora voluptate nesciunt perspiciatis odio id laboriosam veniam? Incidunt, alias quod voluptas eaque harum nam velit, fugit inventore veritatis, magnam iste eveniet corporis hic ex necessitatibus in voluptatem ullam ducimus ipsa ad. Cumque vel maiores accusamus ducimus mollitia optio magni eaque, quae repellendus pariatur. Illum vero possimus facere. Maiores totam et eum adipisci, nesciunt blanditiis atque deleniti, nihil sequi eveniet corrupti dicta itaque illo similique error ex sapiente quo possimus maxime, ratione excepturi beatae. Suscipit consequuntur provident vel temporibus quas autem. Atque accusamus, earum illum nemo cupiditate voluptatibus praesentium laboriosam quibusdam blanditiis? Excepturi aliquam laboriosam dolor ducimus pariatur soluta quasi iure quam quos nemo, harum adipisci sit quidem, reiciendis autem delectus omnis placeat nobis recusandae impedit. Eum ut impedit at esse quidem nihil suscipit voluptatem. Voluptas vero minus porro iure praesentium sit magnam, adipisci esse quidem nisi, laudantium exercitationem repellendus, quod quos? Maxime error exercitationem vel maiores, adipisci quasi accusantium eum commodi ea modi amet eos provident qui pariatur distinctio dignissimos animi illo dolor quam voluptas impedit nisi! Voluptatum!
      </p>
    </div>
  );
}

// svelte/src/routes/Gallery.svelte
<script lang="ts">
</script>

<div class="gallery">
    <img
      src="https://picsum.photos/400/200"
      class="img"
      alt="stock"
    />
    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat inventore deleniti delectus quidem. Minus quo quae esse excepturi assumenda quis repudiandae unde exercitationem, error veniam dolorem harum expedita quam facere, qui beatae quia est. Atque consequatur totam, explicabo tenetur illum libero sit perspiciatis facilis, quibusdam voluptas debitis expedita labore magni fugiat fuga laborum ullam! Blanditiis nulla eius eveniet? Pariatur iste error voluptatem mollitia reiciendis minima libero nulla nihil aperiam ipsa?
    </p>
    <img
      src="https://picsum.photos/400/300"
      class="img"
      alt="stock"
    />
    <p>
      Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fugit, excepturi
      cum doloremque nulla nisi quisquam esse totam aut a nostrum ea voluptas
      aliquam minima consectetur, repudiandae eligendi temporibus dignissimos
      rerum laborum ducimus. Quaerat adipisci eum ipsum totam fuga velit at in
      repudiandae nisi natus quae id sit, explicabo ad laboriosam facere? Commodi
      neque error deleniti corporis accusamus, rerum animi odit asperiores
      molestias sunt. Id magnam, rerum delectus obcaecati incidunt harum minima
      praesentium voluptatum fuga, dicta unde vitae dignissimos exercitationem
      repellendus.
    </p>
    <img
      src="https://picsum.photos/400/500"
      class="img"
      alt="stock"
    />
    <p>
      Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eius excepturi natus quisquam nesciunt unde distinctio corporis, nam impedit rem voluptatem ab voluptatibus animi quae, vitae adipisci perferendis error! Inventore nulla, voluptatem veniam corporis adipisci consequatur itaque repellat. Voluptatum facere sunt soluta, reprehenderit ad, beatae suscipit ea ullam, molestias atque libero quis eum? Nihil quas nemo, fugiat mollitia atque, similique ratione, quaerat tempora voluptate nesciunt perspiciatis odio id laboriosam veniam? Incidunt, alias quod voluptas eaque harum nam velit, fugit inventore veritatis, magnam iste eveniet corporis hic ex necessitatibus in voluptatem ullam ducimus ipsa ad. Cumque vel maiores accusamus ducimus mollitia optio magni eaque, quae repellendus pariatur. Illum vero possimus facere. Maiores totam et eum adipisci, nesciunt blanditiis atque deleniti, nihil sequi eveniet corrupti dicta itaque illo similique error ex sapiente quo possimus maxime, ratione excepturi beatae. Suscipit consequuntur provident vel temporibus quas autem. Atque accusamus, earum illum nemo cupiditate voluptatibus praesentium laboriosam quibusdam blanditiis? Excepturi aliquam laboriosam dolor ducimus pariatur soluta quasi iure quam quos nemo, harum adipisci sit quidem, reiciendis autem delectus omnis placeat nobis recusandae impedit. Eum ut impedit at esse quidem nihil suscipit voluptatem. Voluptas vero minus porro iure praesentium sit magnam, adipisci esse quidem nisi, laudantium exercitationem repellendus, quod quos? Maxime error exercitationem vel maiores, adipisci quasi accusantium eum commodi ea modi amet eos provident qui pariatur distinctio dignissimos animi illo dolor quam voluptas impedit nisi! Voluptatum!
    </p>
</div>

<style>
    .gallery {
        padding-top: 3rem;
        font-size: 1.3rem;
    }

    .gallery p {
        padding: 1rem;
    }

    .img {
        padding: 1rem;
    }

    .img:nth-of-type(1),
    .img:nth-of-type(3) {
        float: right;
    }

    .img:nth-of-type(2) {
        float: left;
    }
</style>
